---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'A template is for creating lambda '
Resources:
    LambdaFunResource:
        Type: AWS::Lambda::Function
        Properties:
        FunctionName: ChinhVCcfn
        Code:
            ZipFile:
            Fn::Join:
            - "\n"
            - - 'def lambda_handler(event, context):'
              - "    print('THIS IS LAMBDA CREATED FROM CloudFormation')"
              - "    return 'success'"
        Description: Used to run job
        Handler: index.lambda_handler
        Role: arn:aws:iam::223320623045:role/chinhvc1RoleExecuteLambda
        Runtime: python3.6
        Timeout: 120
    
